name: MLProjects
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - console_shortcut=0.1.1
  - expat=2.7.3
  - libexpat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.3
  - python=3.10.19
  - python_abi=3.10
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - asttokens==3.0.1
      - astunparse==1.6.3
      - cachetools==6.2.4
      - category-encoders==2.9.0
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - colorama==0.4.6
      - contourpy==1.3.3
      - cycler==0.12.1
      - decorator==5.2.1
      - executing==2.2.1
      - flatbuffers==25.9.23
      - fonttools==4.61.1
      - gast==0.7.0
      - google-auth==2.41.1
      - google-auth-oauthlib==1.2.3
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h5py==3.15.1
      - idna==3.11
      - imageio==2.37.2
      - ipython==9.8.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - joblib==1.5.3
      - keras==2.15.0
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - libclang==18.1.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - ml-dtypes==0.2.0
      - namex==0.1.0
      - networkx==3.6.1
      - numpy==1.26.4
      - oauthlib==3.3.1
      - opencv-python==4.9.0.80
      - opt-einsum==3.4.0
      - optree==0.18.0
      - packaging==25.0
      - pandas==2.3.3
      - pandas-stubs==2.3.3.251201
      - parso==0.8.5
      - patsy==1.0.2
      - pillow==12.0.0
      - prompt-toolkit==3.0.52
      - protobuf==4.25.8
      - pure-eval==0.2.3
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pygments==2.19.2
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rich==14.2.0
      - rsa==4.9.1
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - six==1.17.0
      - stack-data==0.6.3
      - statsmodels==0.14.6
      - tensorboard==2.15.2
      - tensorboard-data-server==0.7.2
      - tensorflow==2.15.0
      - tensorflow-estimator==2.15.0
      - tensorflow-intel==2.15.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - termcolor==3.2.0
      - threadpoolctl==3.6.0
      - tifffile==2025.12.12
      - traitlets==5.14.3
      - types-pytz==2025.2.0.20251108
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.2
      - wcwidth==0.2.14
      - werkzeug==3.1.4
      - wrapt==1.14.2
      - xgboost==3.1.2
prefix: C:\Users\NitroLap\.conda\envs\MLProjects
